name: cedric.mertz
description: tertiary
version: 0.0.1
author: szkyyxvg.mduuqh7c@3srgrjeg.com
language: sql
buildSystem: ''
buildSystemDetails: null
pipelines:
  pipelines/Terence_OsinskiDan_GerussSiu_Franecki_PhD:
    name: Terence_OsinskiDan_GerussSiu_Franecki_PhD
    description: null
    author: szkyyxvg.mduuqh7c@3srgrjeg.com
    mode: batch
    artefactID: ''
    language: sql
    createdAt: '2025-12-05 20:57:34'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
datasets: {}
templates: {}
jobs: {}
gemContainer:
  languageVersion: ''
  gemLibsVersion: ''
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2025-12-05 20:57:33'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline:
  name: sqlPipeline
  description: null
  author: szkyyxvg.mduuqh7c@3srgrjeg.com
  createdAt: '2025-12-05 20:57:33'
dependencies: []
projectDependencies: {}
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
projectConfigurations: {}
